
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const SystemCultureMode = {
  RICE_WHITE: 'RICE_WHITE',
  RICE_PARBO: 'RICE_PARBO'
} as const

export type SystemCultureMode = (typeof SystemCultureMode)[keyof typeof SystemCultureMode]
