
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Producer` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Producer
 * 
 */
export type ProducerModel = runtime.Types.Result.DefaultSelection<Prisma.$ProducerPayload>

export type AggregateProducer = {
  _count: ProducerCountAggregateOutputType | null
  _min: ProducerMinAggregateOutputType | null
  _max: ProducerMaxAggregateOutputType | null
}

export type ProducerMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  isActive: boolean | null
  name: string | null
  search_name: string | null
  companyId: string | null
}

export type ProducerMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  isActive: boolean | null
  name: string | null
  search_name: string | null
  companyId: string | null
}

export type ProducerCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  isActive: number
  name: number
  search_name: number
  companyId: number
  _all: number
}


export type ProducerMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  isActive?: true
  name?: true
  search_name?: true
  companyId?: true
}

export type ProducerMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  isActive?: true
  name?: true
  search_name?: true
  companyId?: true
}

export type ProducerCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  isActive?: true
  name?: true
  search_name?: true
  companyId?: true
  _all?: true
}

export type ProducerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Producer to aggregate.
   */
  where?: Prisma.ProducerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Producers to fetch.
   */
  orderBy?: Prisma.ProducerOrderByWithRelationInput | Prisma.ProducerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProducerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Producers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Producers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Producers
  **/
  _count?: true | ProducerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProducerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProducerMaxAggregateInputType
}

export type GetProducerAggregateType<T extends ProducerAggregateArgs> = {
      [P in keyof T & keyof AggregateProducer]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProducer[P]>
    : Prisma.GetScalarType<T[P], AggregateProducer[P]>
}




export type ProducerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProducerWhereInput
  orderBy?: Prisma.ProducerOrderByWithAggregationInput | Prisma.ProducerOrderByWithAggregationInput[]
  by: Prisma.ProducerScalarFieldEnum[] | Prisma.ProducerScalarFieldEnum
  having?: Prisma.ProducerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProducerCountAggregateInputType | true
  _min?: ProducerMinAggregateInputType
  _max?: ProducerMaxAggregateInputType
}

export type ProducerGroupByOutputType = {
  id: string
  createdAt: Date
  updatedAt: Date
  isActive: boolean
  name: string
  search_name: string
  companyId: string
  _count: ProducerCountAggregateOutputType | null
  _min: ProducerMinAggregateOutputType | null
  _max: ProducerMaxAggregateOutputType | null
}

type GetProducerGroupByPayload<T extends ProducerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProducerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProducerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProducerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProducerGroupByOutputType[P]>
      }
    >
  >



export type ProducerWhereInput = {
  AND?: Prisma.ProducerWhereInput | Prisma.ProducerWhereInput[]
  OR?: Prisma.ProducerWhereInput[]
  NOT?: Prisma.ProducerWhereInput | Prisma.ProducerWhereInput[]
  id?: Prisma.StringFilter<"Producer"> | string
  createdAt?: Prisma.DateTimeFilter<"Producer"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Producer"> | Date | string
  isActive?: Prisma.BoolFilter<"Producer"> | boolean
  name?: Prisma.StringFilter<"Producer"> | string
  search_name?: Prisma.StringFilter<"Producer"> | string
  companyId?: Prisma.StringFilter<"Producer"> | string
  TraceabilityTrackingOptions?: Prisma.TraceabilityTrackingOptionsListRelationFilter
  Company?: Prisma.XOR<Prisma.CompanyScalarRelationFilter, Prisma.CompanyWhereInput>
}

export type ProducerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  name?: Prisma.SortOrder
  search_name?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
  TraceabilityTrackingOptions?: Prisma.TraceabilityTrackingOptionsOrderByRelationAggregateInput
  Company?: Prisma.CompanyOrderByWithRelationInput
}

export type ProducerWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ProducerWhereInput | Prisma.ProducerWhereInput[]
  OR?: Prisma.ProducerWhereInput[]
  NOT?: Prisma.ProducerWhereInput | Prisma.ProducerWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"Producer"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Producer"> | Date | string
  isActive?: Prisma.BoolFilter<"Producer"> | boolean
  name?: Prisma.StringFilter<"Producer"> | string
  search_name?: Prisma.StringFilter<"Producer"> | string
  companyId?: Prisma.StringFilter<"Producer"> | string
  TraceabilityTrackingOptions?: Prisma.TraceabilityTrackingOptionsListRelationFilter
  Company?: Prisma.XOR<Prisma.CompanyScalarRelationFilter, Prisma.CompanyWhereInput>
}, "id">

export type ProducerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  name?: Prisma.SortOrder
  search_name?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
  _count?: Prisma.ProducerCountOrderByAggregateInput
  _max?: Prisma.ProducerMaxOrderByAggregateInput
  _min?: Prisma.ProducerMinOrderByAggregateInput
}

export type ProducerScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProducerScalarWhereWithAggregatesInput | Prisma.ProducerScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProducerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProducerScalarWhereWithAggregatesInput | Prisma.ProducerScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Producer"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Producer"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Producer"> | Date | string
  isActive?: Prisma.BoolWithAggregatesFilter<"Producer"> | boolean
  name?: Prisma.StringWithAggregatesFilter<"Producer"> | string
  search_name?: Prisma.StringWithAggregatesFilter<"Producer"> | string
  companyId?: Prisma.StringWithAggregatesFilter<"Producer"> | string
}

export type ProducerCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  isActive?: boolean
  name: string
  search_name: string
  TraceabilityTrackingOptions?: Prisma.TraceabilityTrackingOptionsCreateNestedManyWithoutDefaultProducerAttributionsInput
  Company: Prisma.CompanyCreateNestedOneWithoutProducersInput
}

export type ProducerUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  isActive?: boolean
  name: string
  search_name: string
  companyId: string
  TraceabilityTrackingOptions?: Prisma.TraceabilityTrackingOptionsUncheckedCreateNestedManyWithoutDefaultProducerAttributionsInput
}

export type ProducerUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  search_name?: Prisma.StringFieldUpdateOperationsInput | string
  TraceabilityTrackingOptions?: Prisma.TraceabilityTrackingOptionsUpdateManyWithoutDefaultProducerAttributionsNestedInput
  Company?: Prisma.CompanyUpdateOneRequiredWithoutProducersNestedInput
}

export type ProducerUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  search_name?: Prisma.StringFieldUpdateOperationsInput | string
  companyId?: Prisma.StringFieldUpdateOperationsInput | string
  TraceabilityTrackingOptions?: Prisma.TraceabilityTrackingOptionsUncheckedUpdateManyWithoutDefaultProducerAttributionsNestedInput
}

export type ProducerCreateManyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  isActive?: boolean
  name: string
  search_name: string
  companyId: string
}

export type ProducerUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  search_name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ProducerUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  search_name?: Prisma.StringFieldUpdateOperationsInput | string
  companyId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ProducerListRelationFilter = {
  every?: Prisma.ProducerWhereInput
  some?: Prisma.ProducerWhereInput
  none?: Prisma.ProducerWhereInput
}

export type ProducerOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProducerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  name?: Prisma.SortOrder
  search_name?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
}

export type ProducerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  name?: Prisma.SortOrder
  search_name?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
}

export type ProducerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  name?: Prisma.SortOrder
  search_name?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
}

export type ProducerCreateNestedManyWithoutCompanyInput = {
  create?: Prisma.XOR<Prisma.ProducerCreateWithoutCompanyInput, Prisma.ProducerUncheckedCreateWithoutCompanyInput> | Prisma.ProducerCreateWithoutCompanyInput[] | Prisma.ProducerUncheckedCreateWithoutCompanyInput[]
  connectOrCreate?: Prisma.ProducerCreateOrConnectWithoutCompanyInput | Prisma.ProducerCreateOrConnectWithoutCompanyInput[]
  createMany?: Prisma.ProducerCreateManyCompanyInputEnvelope
  connect?: Prisma.ProducerWhereUniqueInput | Prisma.ProducerWhereUniqueInput[]
}

export type ProducerUncheckedCreateNestedManyWithoutCompanyInput = {
  create?: Prisma.XOR<Prisma.ProducerCreateWithoutCompanyInput, Prisma.ProducerUncheckedCreateWithoutCompanyInput> | Prisma.ProducerCreateWithoutCompanyInput[] | Prisma.ProducerUncheckedCreateWithoutCompanyInput[]
  connectOrCreate?: Prisma.ProducerCreateOrConnectWithoutCompanyInput | Prisma.ProducerCreateOrConnectWithoutCompanyInput[]
  createMany?: Prisma.ProducerCreateManyCompanyInputEnvelope
  connect?: Prisma.ProducerWhereUniqueInput | Prisma.ProducerWhereUniqueInput[]
}

export type ProducerUpdateManyWithoutCompanyNestedInput = {
  create?: Prisma.XOR<Prisma.ProducerCreateWithoutCompanyInput, Prisma.ProducerUncheckedCreateWithoutCompanyInput> | Prisma.ProducerCreateWithoutCompanyInput[] | Prisma.ProducerUncheckedCreateWithoutCompanyInput[]
  connectOrCreate?: Prisma.ProducerCreateOrConnectWithoutCompanyInput | Prisma.ProducerCreateOrConnectWithoutCompanyInput[]
  upsert?: Prisma.ProducerUpsertWithWhereUniqueWithoutCompanyInput | Prisma.ProducerUpsertWithWhereUniqueWithoutCompanyInput[]
  createMany?: Prisma.ProducerCreateManyCompanyInputEnvelope
  set?: Prisma.ProducerWhereUniqueInput | Prisma.ProducerWhereUniqueInput[]
  disconnect?: Prisma.ProducerWhereUniqueInput | Prisma.ProducerWhereUniqueInput[]
  delete?: Prisma.ProducerWhereUniqueInput | Prisma.ProducerWhereUniqueInput[]
  connect?: Prisma.ProducerWhereUniqueInput | Prisma.ProducerWhereUniqueInput[]
  update?: Prisma.ProducerUpdateWithWhereUniqueWithoutCompanyInput | Prisma.ProducerUpdateWithWhereUniqueWithoutCompanyInput[]
  updateMany?: Prisma.ProducerUpdateManyWithWhereWithoutCompanyInput | Prisma.ProducerUpdateManyWithWhereWithoutCompanyInput[]
  deleteMany?: Prisma.ProducerScalarWhereInput | Prisma.ProducerScalarWhereInput[]
}

export type ProducerUncheckedUpdateManyWithoutCompanyNestedInput = {
  create?: Prisma.XOR<Prisma.ProducerCreateWithoutCompanyInput, Prisma.ProducerUncheckedCreateWithoutCompanyInput> | Prisma.ProducerCreateWithoutCompanyInput[] | Prisma.ProducerUncheckedCreateWithoutCompanyInput[]
  connectOrCreate?: Prisma.ProducerCreateOrConnectWithoutCompanyInput | Prisma.ProducerCreateOrConnectWithoutCompanyInput[]
  upsert?: Prisma.ProducerUpsertWithWhereUniqueWithoutCompanyInput | Prisma.ProducerUpsertWithWhereUniqueWithoutCompanyInput[]
  createMany?: Prisma.ProducerCreateManyCompanyInputEnvelope
  set?: Prisma.ProducerWhereUniqueInput | Prisma.ProducerWhereUniqueInput[]
  disconnect?: Prisma.ProducerWhereUniqueInput | Prisma.ProducerWhereUniqueInput[]
  delete?: Prisma.ProducerWhereUniqueInput | Prisma.ProducerWhereUniqueInput[]
  connect?: Prisma.ProducerWhereUniqueInput | Prisma.ProducerWhereUniqueInput[]
  update?: Prisma.ProducerUpdateWithWhereUniqueWithoutCompanyInput | Prisma.ProducerUpdateWithWhereUniqueWithoutCompanyInput[]
  updateMany?: Prisma.ProducerUpdateManyWithWhereWithoutCompanyInput | Prisma.ProducerUpdateManyWithWhereWithoutCompanyInput[]
  deleteMany?: Prisma.ProducerScalarWhereInput | Prisma.ProducerScalarWhereInput[]
}

export type ProducerCreateNestedManyWithoutTraceabilityTrackingOptionsInput = {
  create?: Prisma.XOR<Prisma.ProducerCreateWithoutTraceabilityTrackingOptionsInput, Prisma.ProducerUncheckedCreateWithoutTraceabilityTrackingOptionsInput> | Prisma.ProducerCreateWithoutTraceabilityTrackingOptionsInput[] | Prisma.ProducerUncheckedCreateWithoutTraceabilityTrackingOptionsInput[]
  connectOrCreate?: Prisma.ProducerCreateOrConnectWithoutTraceabilityTrackingOptionsInput | Prisma.ProducerCreateOrConnectWithoutTraceabilityTrackingOptionsInput[]
  connect?: Prisma.ProducerWhereUniqueInput | Prisma.ProducerWhereUniqueInput[]
}

export type ProducerUncheckedCreateNestedManyWithoutTraceabilityTrackingOptionsInput = {
  create?: Prisma.XOR<Prisma.ProducerCreateWithoutTraceabilityTrackingOptionsInput, Prisma.ProducerUncheckedCreateWithoutTraceabilityTrackingOptionsInput> | Prisma.ProducerCreateWithoutTraceabilityTrackingOptionsInput[] | Prisma.ProducerUncheckedCreateWithoutTraceabilityTrackingOptionsInput[]
  connectOrCreate?: Prisma.ProducerCreateOrConnectWithoutTraceabilityTrackingOptionsInput | Prisma.ProducerCreateOrConnectWithoutTraceabilityTrackingOptionsInput[]
  connect?: Prisma.ProducerWhereUniqueInput | Prisma.ProducerWhereUniqueInput[]
}

export type ProducerUpdateManyWithoutTraceabilityTrackingOptionsNestedInput = {
  create?: Prisma.XOR<Prisma.ProducerCreateWithoutTraceabilityTrackingOptionsInput, Prisma.ProducerUncheckedCreateWithoutTraceabilityTrackingOptionsInput> | Prisma.ProducerCreateWithoutTraceabilityTrackingOptionsInput[] | Prisma.ProducerUncheckedCreateWithoutTraceabilityTrackingOptionsInput[]
  connectOrCreate?: Prisma.ProducerCreateOrConnectWithoutTraceabilityTrackingOptionsInput | Prisma.ProducerCreateOrConnectWithoutTraceabilityTrackingOptionsInput[]
  upsert?: Prisma.ProducerUpsertWithWhereUniqueWithoutTraceabilityTrackingOptionsInput | Prisma.ProducerUpsertWithWhereUniqueWithoutTraceabilityTrackingOptionsInput[]
  set?: Prisma.ProducerWhereUniqueInput | Prisma.ProducerWhereUniqueInput[]
  disconnect?: Prisma.ProducerWhereUniqueInput | Prisma.ProducerWhereUniqueInput[]
  delete?: Prisma.ProducerWhereUniqueInput | Prisma.ProducerWhereUniqueInput[]
  connect?: Prisma.ProducerWhereUniqueInput | Prisma.ProducerWhereUniqueInput[]
  update?: Prisma.ProducerUpdateWithWhereUniqueWithoutTraceabilityTrackingOptionsInput | Prisma.ProducerUpdateWithWhereUniqueWithoutTraceabilityTrackingOptionsInput[]
  updateMany?: Prisma.ProducerUpdateManyWithWhereWithoutTraceabilityTrackingOptionsInput | Prisma.ProducerUpdateManyWithWhereWithoutTraceabilityTrackingOptionsInput[]
  deleteMany?: Prisma.ProducerScalarWhereInput | Prisma.ProducerScalarWhereInput[]
}

export type ProducerUncheckedUpdateManyWithoutTraceabilityTrackingOptionsNestedInput = {
  create?: Prisma.XOR<Prisma.ProducerCreateWithoutTraceabilityTrackingOptionsInput, Prisma.ProducerUncheckedCreateWithoutTraceabilityTrackingOptionsInput> | Prisma.ProducerCreateWithoutTraceabilityTrackingOptionsInput[] | Prisma.ProducerUncheckedCreateWithoutTraceabilityTrackingOptionsInput[]
  connectOrCreate?: Prisma.ProducerCreateOrConnectWithoutTraceabilityTrackingOptionsInput | Prisma.ProducerCreateOrConnectWithoutTraceabilityTrackingOptionsInput[]
  upsert?: Prisma.ProducerUpsertWithWhereUniqueWithoutTraceabilityTrackingOptionsInput | Prisma.ProducerUpsertWithWhereUniqueWithoutTraceabilityTrackingOptionsInput[]
  set?: Prisma.ProducerWhereUniqueInput | Prisma.ProducerWhereUniqueInput[]
  disconnect?: Prisma.ProducerWhereUniqueInput | Prisma.ProducerWhereUniqueInput[]
  delete?: Prisma.ProducerWhereUniqueInput | Prisma.ProducerWhereUniqueInput[]
  connect?: Prisma.ProducerWhereUniqueInput | Prisma.ProducerWhereUniqueInput[]
  update?: Prisma.ProducerUpdateWithWhereUniqueWithoutTraceabilityTrackingOptionsInput | Prisma.ProducerUpdateWithWhereUniqueWithoutTraceabilityTrackingOptionsInput[]
  updateMany?: Prisma.ProducerUpdateManyWithWhereWithoutTraceabilityTrackingOptionsInput | Prisma.ProducerUpdateManyWithWhereWithoutTraceabilityTrackingOptionsInput[]
  deleteMany?: Prisma.ProducerScalarWhereInput | Prisma.ProducerScalarWhereInput[]
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type ProducerCreateWithoutCompanyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  isActive?: boolean
  name: string
  search_name: string
  TraceabilityTrackingOptions?: Prisma.TraceabilityTrackingOptionsCreateNestedManyWithoutDefaultProducerAttributionsInput
}

export type ProducerUncheckedCreateWithoutCompanyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  isActive?: boolean
  name: string
  search_name: string
  TraceabilityTrackingOptions?: Prisma.TraceabilityTrackingOptionsUncheckedCreateNestedManyWithoutDefaultProducerAttributionsInput
}

export type ProducerCreateOrConnectWithoutCompanyInput = {
  where: Prisma.ProducerWhereUniqueInput
  create: Prisma.XOR<Prisma.ProducerCreateWithoutCompanyInput, Prisma.ProducerUncheckedCreateWithoutCompanyInput>
}

export type ProducerCreateManyCompanyInputEnvelope = {
  data: Prisma.ProducerCreateManyCompanyInput | Prisma.ProducerCreateManyCompanyInput[]
  skipDuplicates?: boolean
}

export type ProducerUpsertWithWhereUniqueWithoutCompanyInput = {
  where: Prisma.ProducerWhereUniqueInput
  update: Prisma.XOR<Prisma.ProducerUpdateWithoutCompanyInput, Prisma.ProducerUncheckedUpdateWithoutCompanyInput>
  create: Prisma.XOR<Prisma.ProducerCreateWithoutCompanyInput, Prisma.ProducerUncheckedCreateWithoutCompanyInput>
}

export type ProducerUpdateWithWhereUniqueWithoutCompanyInput = {
  where: Prisma.ProducerWhereUniqueInput
  data: Prisma.XOR<Prisma.ProducerUpdateWithoutCompanyInput, Prisma.ProducerUncheckedUpdateWithoutCompanyInput>
}

export type ProducerUpdateManyWithWhereWithoutCompanyInput = {
  where: Prisma.ProducerScalarWhereInput
  data: Prisma.XOR<Prisma.ProducerUpdateManyMutationInput, Prisma.ProducerUncheckedUpdateManyWithoutCompanyInput>
}

export type ProducerScalarWhereInput = {
  AND?: Prisma.ProducerScalarWhereInput | Prisma.ProducerScalarWhereInput[]
  OR?: Prisma.ProducerScalarWhereInput[]
  NOT?: Prisma.ProducerScalarWhereInput | Prisma.ProducerScalarWhereInput[]
  id?: Prisma.StringFilter<"Producer"> | string
  createdAt?: Prisma.DateTimeFilter<"Producer"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Producer"> | Date | string
  isActive?: Prisma.BoolFilter<"Producer"> | boolean
  name?: Prisma.StringFilter<"Producer"> | string
  search_name?: Prisma.StringFilter<"Producer"> | string
  companyId?: Prisma.StringFilter<"Producer"> | string
}

export type ProducerCreateWithoutTraceabilityTrackingOptionsInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  isActive?: boolean
  name: string
  search_name: string
  Company: Prisma.CompanyCreateNestedOneWithoutProducersInput
}

export type ProducerUncheckedCreateWithoutTraceabilityTrackingOptionsInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  isActive?: boolean
  name: string
  search_name: string
  companyId: string
}

export type ProducerCreateOrConnectWithoutTraceabilityTrackingOptionsInput = {
  where: Prisma.ProducerWhereUniqueInput
  create: Prisma.XOR<Prisma.ProducerCreateWithoutTraceabilityTrackingOptionsInput, Prisma.ProducerUncheckedCreateWithoutTraceabilityTrackingOptionsInput>
}

export type ProducerUpsertWithWhereUniqueWithoutTraceabilityTrackingOptionsInput = {
  where: Prisma.ProducerWhereUniqueInput
  update: Prisma.XOR<Prisma.ProducerUpdateWithoutTraceabilityTrackingOptionsInput, Prisma.ProducerUncheckedUpdateWithoutTraceabilityTrackingOptionsInput>
  create: Prisma.XOR<Prisma.ProducerCreateWithoutTraceabilityTrackingOptionsInput, Prisma.ProducerUncheckedCreateWithoutTraceabilityTrackingOptionsInput>
}

export type ProducerUpdateWithWhereUniqueWithoutTraceabilityTrackingOptionsInput = {
  where: Prisma.ProducerWhereUniqueInput
  data: Prisma.XOR<Prisma.ProducerUpdateWithoutTraceabilityTrackingOptionsInput, Prisma.ProducerUncheckedUpdateWithoutTraceabilityTrackingOptionsInput>
}

export type ProducerUpdateManyWithWhereWithoutTraceabilityTrackingOptionsInput = {
  where: Prisma.ProducerScalarWhereInput
  data: Prisma.XOR<Prisma.ProducerUpdateManyMutationInput, Prisma.ProducerUncheckedUpdateManyWithoutTraceabilityTrackingOptionsInput>
}

export type ProducerCreateManyCompanyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  isActive?: boolean
  name: string
  search_name: string
}

export type ProducerUpdateWithoutCompanyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  search_name?: Prisma.StringFieldUpdateOperationsInput | string
  TraceabilityTrackingOptions?: Prisma.TraceabilityTrackingOptionsUpdateManyWithoutDefaultProducerAttributionsNestedInput
}

export type ProducerUncheckedUpdateWithoutCompanyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  search_name?: Prisma.StringFieldUpdateOperationsInput | string
  TraceabilityTrackingOptions?: Prisma.TraceabilityTrackingOptionsUncheckedUpdateManyWithoutDefaultProducerAttributionsNestedInput
}

export type ProducerUncheckedUpdateManyWithoutCompanyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  search_name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ProducerUpdateWithoutTraceabilityTrackingOptionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  search_name?: Prisma.StringFieldUpdateOperationsInput | string
  Company?: Prisma.CompanyUpdateOneRequiredWithoutProducersNestedInput
}

export type ProducerUncheckedUpdateWithoutTraceabilityTrackingOptionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  search_name?: Prisma.StringFieldUpdateOperationsInput | string
  companyId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ProducerUncheckedUpdateManyWithoutTraceabilityTrackingOptionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  search_name?: Prisma.StringFieldUpdateOperationsInput | string
  companyId?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type ProducerCountOutputType
 */

export type ProducerCountOutputType = {
  TraceabilityTrackingOptions: number
}

export type ProducerCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  TraceabilityTrackingOptions?: boolean | ProducerCountOutputTypeCountTraceabilityTrackingOptionsArgs
}

/**
 * ProducerCountOutputType without action
 */
export type ProducerCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProducerCountOutputType
   */
  select?: Prisma.ProducerCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ProducerCountOutputType without action
 */
export type ProducerCountOutputTypeCountTraceabilityTrackingOptionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TraceabilityTrackingOptionsWhereInput
}


export type ProducerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  isActive?: boolean
  name?: boolean
  search_name?: boolean
  companyId?: boolean
  TraceabilityTrackingOptions?: boolean | Prisma.Producer$TraceabilityTrackingOptionsArgs<ExtArgs>
  Company?: boolean | Prisma.CompanyDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.ProducerCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["producer"]>

export type ProducerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  isActive?: boolean
  name?: boolean
  search_name?: boolean
  companyId?: boolean
  Company?: boolean | Prisma.CompanyDefaultArgs<ExtArgs>
}, ExtArgs["result"]["producer"]>

export type ProducerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  isActive?: boolean
  name?: boolean
  search_name?: boolean
  companyId?: boolean
  Company?: boolean | Prisma.CompanyDefaultArgs<ExtArgs>
}, ExtArgs["result"]["producer"]>

export type ProducerSelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  isActive?: boolean
  name?: boolean
  search_name?: boolean
  companyId?: boolean
}

export type ProducerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "isActive" | "name" | "search_name" | "companyId", ExtArgs["result"]["producer"]>
export type ProducerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  TraceabilityTrackingOptions?: boolean | Prisma.Producer$TraceabilityTrackingOptionsArgs<ExtArgs>
  Company?: boolean | Prisma.CompanyDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.ProducerCountOutputTypeDefaultArgs<ExtArgs>
}
export type ProducerIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Company?: boolean | Prisma.CompanyDefaultArgs<ExtArgs>
}
export type ProducerIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Company?: boolean | Prisma.CompanyDefaultArgs<ExtArgs>
}

export type $ProducerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Producer"
  objects: {
    /**
     * Generic M:N relation to TraceabilityTrackingOptions
     */
    TraceabilityTrackingOptions: Prisma.$TraceabilityTrackingOptionsPayload<ExtArgs>[]
    Company: Prisma.$CompanyPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    updatedAt: Date
    isActive: boolean
    name: string
    search_name: string
    companyId: string
  }, ExtArgs["result"]["producer"]>
  composites: {}
}

export type ProducerGetPayload<S extends boolean | null | undefined | ProducerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProducerPayload, S>

export type ProducerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProducerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProducerCountAggregateInputType | true
  }

export interface ProducerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Producer'], meta: { name: 'Producer' } }
  /**
   * Find zero or one Producer that matches the filter.
   * @param {ProducerFindUniqueArgs} args - Arguments to find a Producer
   * @example
   * // Get one Producer
   * const producer = await prisma.producer.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProducerFindUniqueArgs>(args: Prisma.SelectSubset<T, ProducerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProducerClient<runtime.Types.Result.GetResult<Prisma.$ProducerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Producer that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProducerFindUniqueOrThrowArgs} args - Arguments to find a Producer
   * @example
   * // Get one Producer
   * const producer = await prisma.producer.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProducerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProducerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProducerClient<runtime.Types.Result.GetResult<Prisma.$ProducerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Producer that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProducerFindFirstArgs} args - Arguments to find a Producer
   * @example
   * // Get one Producer
   * const producer = await prisma.producer.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProducerFindFirstArgs>(args?: Prisma.SelectSubset<T, ProducerFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProducerClient<runtime.Types.Result.GetResult<Prisma.$ProducerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Producer that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProducerFindFirstOrThrowArgs} args - Arguments to find a Producer
   * @example
   * // Get one Producer
   * const producer = await prisma.producer.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProducerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProducerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProducerClient<runtime.Types.Result.GetResult<Prisma.$ProducerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Producers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProducerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Producers
   * const producers = await prisma.producer.findMany()
   * 
   * // Get first 10 Producers
   * const producers = await prisma.producer.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const producerWithIdOnly = await prisma.producer.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProducerFindManyArgs>(args?: Prisma.SelectSubset<T, ProducerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProducerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Producer.
   * @param {ProducerCreateArgs} args - Arguments to create a Producer.
   * @example
   * // Create one Producer
   * const Producer = await prisma.producer.create({
   *   data: {
   *     // ... data to create a Producer
   *   }
   * })
   * 
   */
  create<T extends ProducerCreateArgs>(args: Prisma.SelectSubset<T, ProducerCreateArgs<ExtArgs>>): Prisma.Prisma__ProducerClient<runtime.Types.Result.GetResult<Prisma.$ProducerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Producers.
   * @param {ProducerCreateManyArgs} args - Arguments to create many Producers.
   * @example
   * // Create many Producers
   * const producer = await prisma.producer.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProducerCreateManyArgs>(args?: Prisma.SelectSubset<T, ProducerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Producers and returns the data saved in the database.
   * @param {ProducerCreateManyAndReturnArgs} args - Arguments to create many Producers.
   * @example
   * // Create many Producers
   * const producer = await prisma.producer.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Producers and only return the `id`
   * const producerWithIdOnly = await prisma.producer.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProducerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProducerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProducerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Producer.
   * @param {ProducerDeleteArgs} args - Arguments to delete one Producer.
   * @example
   * // Delete one Producer
   * const Producer = await prisma.producer.delete({
   *   where: {
   *     // ... filter to delete one Producer
   *   }
   * })
   * 
   */
  delete<T extends ProducerDeleteArgs>(args: Prisma.SelectSubset<T, ProducerDeleteArgs<ExtArgs>>): Prisma.Prisma__ProducerClient<runtime.Types.Result.GetResult<Prisma.$ProducerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Producer.
   * @param {ProducerUpdateArgs} args - Arguments to update one Producer.
   * @example
   * // Update one Producer
   * const producer = await prisma.producer.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProducerUpdateArgs>(args: Prisma.SelectSubset<T, ProducerUpdateArgs<ExtArgs>>): Prisma.Prisma__ProducerClient<runtime.Types.Result.GetResult<Prisma.$ProducerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Producers.
   * @param {ProducerDeleteManyArgs} args - Arguments to filter Producers to delete.
   * @example
   * // Delete a few Producers
   * const { count } = await prisma.producer.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProducerDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProducerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Producers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProducerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Producers
   * const producer = await prisma.producer.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProducerUpdateManyArgs>(args: Prisma.SelectSubset<T, ProducerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Producers and returns the data updated in the database.
   * @param {ProducerUpdateManyAndReturnArgs} args - Arguments to update many Producers.
   * @example
   * // Update many Producers
   * const producer = await prisma.producer.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Producers and only return the `id`
   * const producerWithIdOnly = await prisma.producer.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProducerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProducerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProducerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Producer.
   * @param {ProducerUpsertArgs} args - Arguments to update or create a Producer.
   * @example
   * // Update or create a Producer
   * const producer = await prisma.producer.upsert({
   *   create: {
   *     // ... data to create a Producer
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Producer we want to update
   *   }
   * })
   */
  upsert<T extends ProducerUpsertArgs>(args: Prisma.SelectSubset<T, ProducerUpsertArgs<ExtArgs>>): Prisma.Prisma__ProducerClient<runtime.Types.Result.GetResult<Prisma.$ProducerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Producers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProducerCountArgs} args - Arguments to filter Producers to count.
   * @example
   * // Count the number of Producers
   * const count = await prisma.producer.count({
   *   where: {
   *     // ... the filter for the Producers we want to count
   *   }
   * })
  **/
  count<T extends ProducerCountArgs>(
    args?: Prisma.Subset<T, ProducerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProducerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Producer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProducerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProducerAggregateArgs>(args: Prisma.Subset<T, ProducerAggregateArgs>): Prisma.PrismaPromise<GetProducerAggregateType<T>>

  /**
   * Group by Producer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProducerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProducerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProducerGroupByArgs['orderBy'] }
      : { orderBy?: ProducerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProducerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProducerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Producer model
 */
readonly fields: ProducerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Producer.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProducerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  TraceabilityTrackingOptions<T extends Prisma.Producer$TraceabilityTrackingOptionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Producer$TraceabilityTrackingOptionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TraceabilityTrackingOptionsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  Company<T extends Prisma.CompanyDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CompanyDefaultArgs<ExtArgs>>): Prisma.Prisma__CompanyClient<runtime.Types.Result.GetResult<Prisma.$CompanyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Producer model
 */
export interface ProducerFieldRefs {
  readonly id: Prisma.FieldRef<"Producer", 'String'>
  readonly createdAt: Prisma.FieldRef<"Producer", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Producer", 'DateTime'>
  readonly isActive: Prisma.FieldRef<"Producer", 'Boolean'>
  readonly name: Prisma.FieldRef<"Producer", 'String'>
  readonly search_name: Prisma.FieldRef<"Producer", 'String'>
  readonly companyId: Prisma.FieldRef<"Producer", 'String'>
}
    

// Custom InputTypes
/**
 * Producer findUnique
 */
export type ProducerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Producer
   */
  select?: Prisma.ProducerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Producer
   */
  omit?: Prisma.ProducerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProducerInclude<ExtArgs> | null
  /**
   * Filter, which Producer to fetch.
   */
  where: Prisma.ProducerWhereUniqueInput
}

/**
 * Producer findUniqueOrThrow
 */
export type ProducerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Producer
   */
  select?: Prisma.ProducerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Producer
   */
  omit?: Prisma.ProducerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProducerInclude<ExtArgs> | null
  /**
   * Filter, which Producer to fetch.
   */
  where: Prisma.ProducerWhereUniqueInput
}

/**
 * Producer findFirst
 */
export type ProducerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Producer
   */
  select?: Prisma.ProducerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Producer
   */
  omit?: Prisma.ProducerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProducerInclude<ExtArgs> | null
  /**
   * Filter, which Producer to fetch.
   */
  where?: Prisma.ProducerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Producers to fetch.
   */
  orderBy?: Prisma.ProducerOrderByWithRelationInput | Prisma.ProducerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Producers.
   */
  cursor?: Prisma.ProducerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Producers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Producers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Producers.
   */
  distinct?: Prisma.ProducerScalarFieldEnum | Prisma.ProducerScalarFieldEnum[]
}

/**
 * Producer findFirstOrThrow
 */
export type ProducerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Producer
   */
  select?: Prisma.ProducerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Producer
   */
  omit?: Prisma.ProducerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProducerInclude<ExtArgs> | null
  /**
   * Filter, which Producer to fetch.
   */
  where?: Prisma.ProducerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Producers to fetch.
   */
  orderBy?: Prisma.ProducerOrderByWithRelationInput | Prisma.ProducerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Producers.
   */
  cursor?: Prisma.ProducerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Producers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Producers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Producers.
   */
  distinct?: Prisma.ProducerScalarFieldEnum | Prisma.ProducerScalarFieldEnum[]
}

/**
 * Producer findMany
 */
export type ProducerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Producer
   */
  select?: Prisma.ProducerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Producer
   */
  omit?: Prisma.ProducerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProducerInclude<ExtArgs> | null
  /**
   * Filter, which Producers to fetch.
   */
  where?: Prisma.ProducerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Producers to fetch.
   */
  orderBy?: Prisma.ProducerOrderByWithRelationInput | Prisma.ProducerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Producers.
   */
  cursor?: Prisma.ProducerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Producers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Producers.
   */
  skip?: number
  distinct?: Prisma.ProducerScalarFieldEnum | Prisma.ProducerScalarFieldEnum[]
}

/**
 * Producer create
 */
export type ProducerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Producer
   */
  select?: Prisma.ProducerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Producer
   */
  omit?: Prisma.ProducerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProducerInclude<ExtArgs> | null
  /**
   * The data needed to create a Producer.
   */
  data: Prisma.XOR<Prisma.ProducerCreateInput, Prisma.ProducerUncheckedCreateInput>
}

/**
 * Producer createMany
 */
export type ProducerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Producers.
   */
  data: Prisma.ProducerCreateManyInput | Prisma.ProducerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Producer createManyAndReturn
 */
export type ProducerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Producer
   */
  select?: Prisma.ProducerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Producer
   */
  omit?: Prisma.ProducerOmit<ExtArgs> | null
  /**
   * The data used to create many Producers.
   */
  data: Prisma.ProducerCreateManyInput | Prisma.ProducerCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProducerIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Producer update
 */
export type ProducerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Producer
   */
  select?: Prisma.ProducerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Producer
   */
  omit?: Prisma.ProducerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProducerInclude<ExtArgs> | null
  /**
   * The data needed to update a Producer.
   */
  data: Prisma.XOR<Prisma.ProducerUpdateInput, Prisma.ProducerUncheckedUpdateInput>
  /**
   * Choose, which Producer to update.
   */
  where: Prisma.ProducerWhereUniqueInput
}

/**
 * Producer updateMany
 */
export type ProducerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Producers.
   */
  data: Prisma.XOR<Prisma.ProducerUpdateManyMutationInput, Prisma.ProducerUncheckedUpdateManyInput>
  /**
   * Filter which Producers to update
   */
  where?: Prisma.ProducerWhereInput
  /**
   * Limit how many Producers to update.
   */
  limit?: number
}

/**
 * Producer updateManyAndReturn
 */
export type ProducerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Producer
   */
  select?: Prisma.ProducerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Producer
   */
  omit?: Prisma.ProducerOmit<ExtArgs> | null
  /**
   * The data used to update Producers.
   */
  data: Prisma.XOR<Prisma.ProducerUpdateManyMutationInput, Prisma.ProducerUncheckedUpdateManyInput>
  /**
   * Filter which Producers to update
   */
  where?: Prisma.ProducerWhereInput
  /**
   * Limit how many Producers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProducerIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Producer upsert
 */
export type ProducerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Producer
   */
  select?: Prisma.ProducerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Producer
   */
  omit?: Prisma.ProducerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProducerInclude<ExtArgs> | null
  /**
   * The filter to search for the Producer to update in case it exists.
   */
  where: Prisma.ProducerWhereUniqueInput
  /**
   * In case the Producer found by the `where` argument doesn't exist, create a new Producer with this data.
   */
  create: Prisma.XOR<Prisma.ProducerCreateInput, Prisma.ProducerUncheckedCreateInput>
  /**
   * In case the Producer was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProducerUpdateInput, Prisma.ProducerUncheckedUpdateInput>
}

/**
 * Producer delete
 */
export type ProducerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Producer
   */
  select?: Prisma.ProducerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Producer
   */
  omit?: Prisma.ProducerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProducerInclude<ExtArgs> | null
  /**
   * Filter which Producer to delete.
   */
  where: Prisma.ProducerWhereUniqueInput
}

/**
 * Producer deleteMany
 */
export type ProducerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Producers to delete
   */
  where?: Prisma.ProducerWhereInput
  /**
   * Limit how many Producers to delete.
   */
  limit?: number
}

/**
 * Producer.TraceabilityTrackingOptions
 */
export type Producer$TraceabilityTrackingOptionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TraceabilityTrackingOptions
   */
  select?: Prisma.TraceabilityTrackingOptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TraceabilityTrackingOptions
   */
  omit?: Prisma.TraceabilityTrackingOptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TraceabilityTrackingOptionsInclude<ExtArgs> | null
  where?: Prisma.TraceabilityTrackingOptionsWhereInput
  orderBy?: Prisma.TraceabilityTrackingOptionsOrderByWithRelationInput | Prisma.TraceabilityTrackingOptionsOrderByWithRelationInput[]
  cursor?: Prisma.TraceabilityTrackingOptionsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TraceabilityTrackingOptionsScalarFieldEnum | Prisma.TraceabilityTrackingOptionsScalarFieldEnum[]
}

/**
 * Producer without action
 */
export type ProducerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Producer
   */
  select?: Prisma.ProducerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Producer
   */
  omit?: Prisma.ProducerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProducerInclude<ExtArgs> | null
}
