
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TraceabilityTrackingOptions` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TraceabilityTrackingOptions
 * 
 */
export type TraceabilityTrackingOptionsModel = runtime.Types.Result.DefaultSelection<Prisma.$TraceabilityTrackingOptionsPayload>

export type AggregateTraceabilityTrackingOptions = {
  _count: TraceabilityTrackingOptionsCountAggregateOutputType | null
  _min: TraceabilityTrackingOptionsMinAggregateOutputType | null
  _max: TraceabilityTrackingOptionsMaxAggregateOutputType | null
}

export type TraceabilityTrackingOptionsMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  SystemCultureMode: $Enums.SystemCultureMode | null
  companyId: string | null
}

export type TraceabilityTrackingOptionsMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  SystemCultureMode: $Enums.SystemCultureMode | null
  companyId: string | null
}

export type TraceabilityTrackingOptionsCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  SystemCultureMode: number
  companyId: number
  _all: number
}


export type TraceabilityTrackingOptionsMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  SystemCultureMode?: true
  companyId?: true
}

export type TraceabilityTrackingOptionsMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  SystemCultureMode?: true
  companyId?: true
}

export type TraceabilityTrackingOptionsCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  SystemCultureMode?: true
  companyId?: true
  _all?: true
}

export type TraceabilityTrackingOptionsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TraceabilityTrackingOptions to aggregate.
   */
  where?: Prisma.TraceabilityTrackingOptionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TraceabilityTrackingOptions to fetch.
   */
  orderBy?: Prisma.TraceabilityTrackingOptionsOrderByWithRelationInput | Prisma.TraceabilityTrackingOptionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TraceabilityTrackingOptionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TraceabilityTrackingOptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TraceabilityTrackingOptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TraceabilityTrackingOptions
  **/
  _count?: true | TraceabilityTrackingOptionsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TraceabilityTrackingOptionsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TraceabilityTrackingOptionsMaxAggregateInputType
}

export type GetTraceabilityTrackingOptionsAggregateType<T extends TraceabilityTrackingOptionsAggregateArgs> = {
      [P in keyof T & keyof AggregateTraceabilityTrackingOptions]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTraceabilityTrackingOptions[P]>
    : Prisma.GetScalarType<T[P], AggregateTraceabilityTrackingOptions[P]>
}




export type TraceabilityTrackingOptionsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TraceabilityTrackingOptionsWhereInput
  orderBy?: Prisma.TraceabilityTrackingOptionsOrderByWithAggregationInput | Prisma.TraceabilityTrackingOptionsOrderByWithAggregationInput[]
  by: Prisma.TraceabilityTrackingOptionsScalarFieldEnum[] | Prisma.TraceabilityTrackingOptionsScalarFieldEnum
  having?: Prisma.TraceabilityTrackingOptionsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TraceabilityTrackingOptionsCountAggregateInputType | true
  _min?: TraceabilityTrackingOptionsMinAggregateInputType
  _max?: TraceabilityTrackingOptionsMaxAggregateInputType
}

export type TraceabilityTrackingOptionsGroupByOutputType = {
  id: string
  createdAt: Date
  updatedAt: Date
  SystemCultureMode: $Enums.SystemCultureMode
  companyId: string
  _count: TraceabilityTrackingOptionsCountAggregateOutputType | null
  _min: TraceabilityTrackingOptionsMinAggregateOutputType | null
  _max: TraceabilityTrackingOptionsMaxAggregateOutputType | null
}

type GetTraceabilityTrackingOptionsGroupByPayload<T extends TraceabilityTrackingOptionsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TraceabilityTrackingOptionsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TraceabilityTrackingOptionsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TraceabilityTrackingOptionsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TraceabilityTrackingOptionsGroupByOutputType[P]>
      }
    >
  >



export type TraceabilityTrackingOptionsWhereInput = {
  AND?: Prisma.TraceabilityTrackingOptionsWhereInput | Prisma.TraceabilityTrackingOptionsWhereInput[]
  OR?: Prisma.TraceabilityTrackingOptionsWhereInput[]
  NOT?: Prisma.TraceabilityTrackingOptionsWhereInput | Prisma.TraceabilityTrackingOptionsWhereInput[]
  id?: Prisma.StringFilter<"TraceabilityTrackingOptions"> | string
  createdAt?: Prisma.DateTimeFilter<"TraceabilityTrackingOptions"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TraceabilityTrackingOptions"> | Date | string
  SystemCultureMode?: Prisma.EnumSystemCultureModeFilter<"TraceabilityTrackingOptions"> | $Enums.SystemCultureMode
  companyId?: Prisma.StringFilter<"TraceabilityTrackingOptions"> | string
  DefaultProducerAttributions?: Prisma.ProducerListRelationFilter
  Company?: Prisma.XOR<Prisma.CompanyScalarRelationFilter, Prisma.CompanyWhereInput>
}

export type TraceabilityTrackingOptionsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  SystemCultureMode?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
  DefaultProducerAttributions?: Prisma.ProducerOrderByRelationAggregateInput
  Company?: Prisma.CompanyOrderByWithRelationInput
}

export type TraceabilityTrackingOptionsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  SystemCultureMode_companyId?: Prisma.TraceabilityTrackingOptionsSystemCultureModeCompanyIdCompoundUniqueInput
  AND?: Prisma.TraceabilityTrackingOptionsWhereInput | Prisma.TraceabilityTrackingOptionsWhereInput[]
  OR?: Prisma.TraceabilityTrackingOptionsWhereInput[]
  NOT?: Prisma.TraceabilityTrackingOptionsWhereInput | Prisma.TraceabilityTrackingOptionsWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"TraceabilityTrackingOptions"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TraceabilityTrackingOptions"> | Date | string
  SystemCultureMode?: Prisma.EnumSystemCultureModeFilter<"TraceabilityTrackingOptions"> | $Enums.SystemCultureMode
  companyId?: Prisma.StringFilter<"TraceabilityTrackingOptions"> | string
  DefaultProducerAttributions?: Prisma.ProducerListRelationFilter
  Company?: Prisma.XOR<Prisma.CompanyScalarRelationFilter, Prisma.CompanyWhereInput>
}, "id" | "SystemCultureMode_companyId">

export type TraceabilityTrackingOptionsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  SystemCultureMode?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
  _count?: Prisma.TraceabilityTrackingOptionsCountOrderByAggregateInput
  _max?: Prisma.TraceabilityTrackingOptionsMaxOrderByAggregateInput
  _min?: Prisma.TraceabilityTrackingOptionsMinOrderByAggregateInput
}

export type TraceabilityTrackingOptionsScalarWhereWithAggregatesInput = {
  AND?: Prisma.TraceabilityTrackingOptionsScalarWhereWithAggregatesInput | Prisma.TraceabilityTrackingOptionsScalarWhereWithAggregatesInput[]
  OR?: Prisma.TraceabilityTrackingOptionsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TraceabilityTrackingOptionsScalarWhereWithAggregatesInput | Prisma.TraceabilityTrackingOptionsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TraceabilityTrackingOptions"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TraceabilityTrackingOptions"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TraceabilityTrackingOptions"> | Date | string
  SystemCultureMode?: Prisma.EnumSystemCultureModeWithAggregatesFilter<"TraceabilityTrackingOptions"> | $Enums.SystemCultureMode
  companyId?: Prisma.StringWithAggregatesFilter<"TraceabilityTrackingOptions"> | string
}

export type TraceabilityTrackingOptionsCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  SystemCultureMode?: $Enums.SystemCultureMode
  DefaultProducerAttributions?: Prisma.ProducerCreateNestedManyWithoutTraceabilityTrackingOptionsInput
  Company: Prisma.CompanyCreateNestedOneWithoutTraceabilityTrackingOptionsInput
}

export type TraceabilityTrackingOptionsUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  SystemCultureMode?: $Enums.SystemCultureMode
  companyId: string
  DefaultProducerAttributions?: Prisma.ProducerUncheckedCreateNestedManyWithoutTraceabilityTrackingOptionsInput
}

export type TraceabilityTrackingOptionsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  SystemCultureMode?: Prisma.EnumSystemCultureModeFieldUpdateOperationsInput | $Enums.SystemCultureMode
  DefaultProducerAttributions?: Prisma.ProducerUpdateManyWithoutTraceabilityTrackingOptionsNestedInput
  Company?: Prisma.CompanyUpdateOneRequiredWithoutTraceabilityTrackingOptionsNestedInput
}

export type TraceabilityTrackingOptionsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  SystemCultureMode?: Prisma.EnumSystemCultureModeFieldUpdateOperationsInput | $Enums.SystemCultureMode
  companyId?: Prisma.StringFieldUpdateOperationsInput | string
  DefaultProducerAttributions?: Prisma.ProducerUncheckedUpdateManyWithoutTraceabilityTrackingOptionsNestedInput
}

export type TraceabilityTrackingOptionsCreateManyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  SystemCultureMode?: $Enums.SystemCultureMode
  companyId: string
}

export type TraceabilityTrackingOptionsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  SystemCultureMode?: Prisma.EnumSystemCultureModeFieldUpdateOperationsInput | $Enums.SystemCultureMode
}

export type TraceabilityTrackingOptionsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  SystemCultureMode?: Prisma.EnumSystemCultureModeFieldUpdateOperationsInput | $Enums.SystemCultureMode
  companyId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TraceabilityTrackingOptionsListRelationFilter = {
  every?: Prisma.TraceabilityTrackingOptionsWhereInput
  some?: Prisma.TraceabilityTrackingOptionsWhereInput
  none?: Prisma.TraceabilityTrackingOptionsWhereInput
}

export type TraceabilityTrackingOptionsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TraceabilityTrackingOptionsSystemCultureModeCompanyIdCompoundUniqueInput = {
  SystemCultureMode: $Enums.SystemCultureMode
  companyId: string
}

export type TraceabilityTrackingOptionsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  SystemCultureMode?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
}

export type TraceabilityTrackingOptionsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  SystemCultureMode?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
}

export type TraceabilityTrackingOptionsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  SystemCultureMode?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
}

export type TraceabilityTrackingOptionsCreateNestedManyWithoutCompanyInput = {
  create?: Prisma.XOR<Prisma.TraceabilityTrackingOptionsCreateWithoutCompanyInput, Prisma.TraceabilityTrackingOptionsUncheckedCreateWithoutCompanyInput> | Prisma.TraceabilityTrackingOptionsCreateWithoutCompanyInput[] | Prisma.TraceabilityTrackingOptionsUncheckedCreateWithoutCompanyInput[]
  connectOrCreate?: Prisma.TraceabilityTrackingOptionsCreateOrConnectWithoutCompanyInput | Prisma.TraceabilityTrackingOptionsCreateOrConnectWithoutCompanyInput[]
  createMany?: Prisma.TraceabilityTrackingOptionsCreateManyCompanyInputEnvelope
  connect?: Prisma.TraceabilityTrackingOptionsWhereUniqueInput | Prisma.TraceabilityTrackingOptionsWhereUniqueInput[]
}

export type TraceabilityTrackingOptionsUncheckedCreateNestedManyWithoutCompanyInput = {
  create?: Prisma.XOR<Prisma.TraceabilityTrackingOptionsCreateWithoutCompanyInput, Prisma.TraceabilityTrackingOptionsUncheckedCreateWithoutCompanyInput> | Prisma.TraceabilityTrackingOptionsCreateWithoutCompanyInput[] | Prisma.TraceabilityTrackingOptionsUncheckedCreateWithoutCompanyInput[]
  connectOrCreate?: Prisma.TraceabilityTrackingOptionsCreateOrConnectWithoutCompanyInput | Prisma.TraceabilityTrackingOptionsCreateOrConnectWithoutCompanyInput[]
  createMany?: Prisma.TraceabilityTrackingOptionsCreateManyCompanyInputEnvelope
  connect?: Prisma.TraceabilityTrackingOptionsWhereUniqueInput | Prisma.TraceabilityTrackingOptionsWhereUniqueInput[]
}

export type TraceabilityTrackingOptionsUpdateManyWithoutCompanyNestedInput = {
  create?: Prisma.XOR<Prisma.TraceabilityTrackingOptionsCreateWithoutCompanyInput, Prisma.TraceabilityTrackingOptionsUncheckedCreateWithoutCompanyInput> | Prisma.TraceabilityTrackingOptionsCreateWithoutCompanyInput[] | Prisma.TraceabilityTrackingOptionsUncheckedCreateWithoutCompanyInput[]
  connectOrCreate?: Prisma.TraceabilityTrackingOptionsCreateOrConnectWithoutCompanyInput | Prisma.TraceabilityTrackingOptionsCreateOrConnectWithoutCompanyInput[]
  upsert?: Prisma.TraceabilityTrackingOptionsUpsertWithWhereUniqueWithoutCompanyInput | Prisma.TraceabilityTrackingOptionsUpsertWithWhereUniqueWithoutCompanyInput[]
  createMany?: Prisma.TraceabilityTrackingOptionsCreateManyCompanyInputEnvelope
  set?: Prisma.TraceabilityTrackingOptionsWhereUniqueInput | Prisma.TraceabilityTrackingOptionsWhereUniqueInput[]
  disconnect?: Prisma.TraceabilityTrackingOptionsWhereUniqueInput | Prisma.TraceabilityTrackingOptionsWhereUniqueInput[]
  delete?: Prisma.TraceabilityTrackingOptionsWhereUniqueInput | Prisma.TraceabilityTrackingOptionsWhereUniqueInput[]
  connect?: Prisma.TraceabilityTrackingOptionsWhereUniqueInput | Prisma.TraceabilityTrackingOptionsWhereUniqueInput[]
  update?: Prisma.TraceabilityTrackingOptionsUpdateWithWhereUniqueWithoutCompanyInput | Prisma.TraceabilityTrackingOptionsUpdateWithWhereUniqueWithoutCompanyInput[]
  updateMany?: Prisma.TraceabilityTrackingOptionsUpdateManyWithWhereWithoutCompanyInput | Prisma.TraceabilityTrackingOptionsUpdateManyWithWhereWithoutCompanyInput[]
  deleteMany?: Prisma.TraceabilityTrackingOptionsScalarWhereInput | Prisma.TraceabilityTrackingOptionsScalarWhereInput[]
}

export type TraceabilityTrackingOptionsUncheckedUpdateManyWithoutCompanyNestedInput = {
  create?: Prisma.XOR<Prisma.TraceabilityTrackingOptionsCreateWithoutCompanyInput, Prisma.TraceabilityTrackingOptionsUncheckedCreateWithoutCompanyInput> | Prisma.TraceabilityTrackingOptionsCreateWithoutCompanyInput[] | Prisma.TraceabilityTrackingOptionsUncheckedCreateWithoutCompanyInput[]
  connectOrCreate?: Prisma.TraceabilityTrackingOptionsCreateOrConnectWithoutCompanyInput | Prisma.TraceabilityTrackingOptionsCreateOrConnectWithoutCompanyInput[]
  upsert?: Prisma.TraceabilityTrackingOptionsUpsertWithWhereUniqueWithoutCompanyInput | Prisma.TraceabilityTrackingOptionsUpsertWithWhereUniqueWithoutCompanyInput[]
  createMany?: Prisma.TraceabilityTrackingOptionsCreateManyCompanyInputEnvelope
  set?: Prisma.TraceabilityTrackingOptionsWhereUniqueInput | Prisma.TraceabilityTrackingOptionsWhereUniqueInput[]
  disconnect?: Prisma.TraceabilityTrackingOptionsWhereUniqueInput | Prisma.TraceabilityTrackingOptionsWhereUniqueInput[]
  delete?: Prisma.TraceabilityTrackingOptionsWhereUniqueInput | Prisma.TraceabilityTrackingOptionsWhereUniqueInput[]
  connect?: Prisma.TraceabilityTrackingOptionsWhereUniqueInput | Prisma.TraceabilityTrackingOptionsWhereUniqueInput[]
  update?: Prisma.TraceabilityTrackingOptionsUpdateWithWhereUniqueWithoutCompanyInput | Prisma.TraceabilityTrackingOptionsUpdateWithWhereUniqueWithoutCompanyInput[]
  updateMany?: Prisma.TraceabilityTrackingOptionsUpdateManyWithWhereWithoutCompanyInput | Prisma.TraceabilityTrackingOptionsUpdateManyWithWhereWithoutCompanyInput[]
  deleteMany?: Prisma.TraceabilityTrackingOptionsScalarWhereInput | Prisma.TraceabilityTrackingOptionsScalarWhereInput[]
}

export type EnumSystemCultureModeFieldUpdateOperationsInput = {
  set?: $Enums.SystemCultureMode
}

export type TraceabilityTrackingOptionsCreateNestedManyWithoutDefaultProducerAttributionsInput = {
  create?: Prisma.XOR<Prisma.TraceabilityTrackingOptionsCreateWithoutDefaultProducerAttributionsInput, Prisma.TraceabilityTrackingOptionsUncheckedCreateWithoutDefaultProducerAttributionsInput> | Prisma.TraceabilityTrackingOptionsCreateWithoutDefaultProducerAttributionsInput[] | Prisma.TraceabilityTrackingOptionsUncheckedCreateWithoutDefaultProducerAttributionsInput[]
  connectOrCreate?: Prisma.TraceabilityTrackingOptionsCreateOrConnectWithoutDefaultProducerAttributionsInput | Prisma.TraceabilityTrackingOptionsCreateOrConnectWithoutDefaultProducerAttributionsInput[]
  connect?: Prisma.TraceabilityTrackingOptionsWhereUniqueInput | Prisma.TraceabilityTrackingOptionsWhereUniqueInput[]
}

export type TraceabilityTrackingOptionsUncheckedCreateNestedManyWithoutDefaultProducerAttributionsInput = {
  create?: Prisma.XOR<Prisma.TraceabilityTrackingOptionsCreateWithoutDefaultProducerAttributionsInput, Prisma.TraceabilityTrackingOptionsUncheckedCreateWithoutDefaultProducerAttributionsInput> | Prisma.TraceabilityTrackingOptionsCreateWithoutDefaultProducerAttributionsInput[] | Prisma.TraceabilityTrackingOptionsUncheckedCreateWithoutDefaultProducerAttributionsInput[]
  connectOrCreate?: Prisma.TraceabilityTrackingOptionsCreateOrConnectWithoutDefaultProducerAttributionsInput | Prisma.TraceabilityTrackingOptionsCreateOrConnectWithoutDefaultProducerAttributionsInput[]
  connect?: Prisma.TraceabilityTrackingOptionsWhereUniqueInput | Prisma.TraceabilityTrackingOptionsWhereUniqueInput[]
}

export type TraceabilityTrackingOptionsUpdateManyWithoutDefaultProducerAttributionsNestedInput = {
  create?: Prisma.XOR<Prisma.TraceabilityTrackingOptionsCreateWithoutDefaultProducerAttributionsInput, Prisma.TraceabilityTrackingOptionsUncheckedCreateWithoutDefaultProducerAttributionsInput> | Prisma.TraceabilityTrackingOptionsCreateWithoutDefaultProducerAttributionsInput[] | Prisma.TraceabilityTrackingOptionsUncheckedCreateWithoutDefaultProducerAttributionsInput[]
  connectOrCreate?: Prisma.TraceabilityTrackingOptionsCreateOrConnectWithoutDefaultProducerAttributionsInput | Prisma.TraceabilityTrackingOptionsCreateOrConnectWithoutDefaultProducerAttributionsInput[]
  upsert?: Prisma.TraceabilityTrackingOptionsUpsertWithWhereUniqueWithoutDefaultProducerAttributionsInput | Prisma.TraceabilityTrackingOptionsUpsertWithWhereUniqueWithoutDefaultProducerAttributionsInput[]
  set?: Prisma.TraceabilityTrackingOptionsWhereUniqueInput | Prisma.TraceabilityTrackingOptionsWhereUniqueInput[]
  disconnect?: Prisma.TraceabilityTrackingOptionsWhereUniqueInput | Prisma.TraceabilityTrackingOptionsWhereUniqueInput[]
  delete?: Prisma.TraceabilityTrackingOptionsWhereUniqueInput | Prisma.TraceabilityTrackingOptionsWhereUniqueInput[]
  connect?: Prisma.TraceabilityTrackingOptionsWhereUniqueInput | Prisma.TraceabilityTrackingOptionsWhereUniqueInput[]
  update?: Prisma.TraceabilityTrackingOptionsUpdateWithWhereUniqueWithoutDefaultProducerAttributionsInput | Prisma.TraceabilityTrackingOptionsUpdateWithWhereUniqueWithoutDefaultProducerAttributionsInput[]
  updateMany?: Prisma.TraceabilityTrackingOptionsUpdateManyWithWhereWithoutDefaultProducerAttributionsInput | Prisma.TraceabilityTrackingOptionsUpdateManyWithWhereWithoutDefaultProducerAttributionsInput[]
  deleteMany?: Prisma.TraceabilityTrackingOptionsScalarWhereInput | Prisma.TraceabilityTrackingOptionsScalarWhereInput[]
}

export type TraceabilityTrackingOptionsUncheckedUpdateManyWithoutDefaultProducerAttributionsNestedInput = {
  create?: Prisma.XOR<Prisma.TraceabilityTrackingOptionsCreateWithoutDefaultProducerAttributionsInput, Prisma.TraceabilityTrackingOptionsUncheckedCreateWithoutDefaultProducerAttributionsInput> | Prisma.TraceabilityTrackingOptionsCreateWithoutDefaultProducerAttributionsInput[] | Prisma.TraceabilityTrackingOptionsUncheckedCreateWithoutDefaultProducerAttributionsInput[]
  connectOrCreate?: Prisma.TraceabilityTrackingOptionsCreateOrConnectWithoutDefaultProducerAttributionsInput | Prisma.TraceabilityTrackingOptionsCreateOrConnectWithoutDefaultProducerAttributionsInput[]
  upsert?: Prisma.TraceabilityTrackingOptionsUpsertWithWhereUniqueWithoutDefaultProducerAttributionsInput | Prisma.TraceabilityTrackingOptionsUpsertWithWhereUniqueWithoutDefaultProducerAttributionsInput[]
  set?: Prisma.TraceabilityTrackingOptionsWhereUniqueInput | Prisma.TraceabilityTrackingOptionsWhereUniqueInput[]
  disconnect?: Prisma.TraceabilityTrackingOptionsWhereUniqueInput | Prisma.TraceabilityTrackingOptionsWhereUniqueInput[]
  delete?: Prisma.TraceabilityTrackingOptionsWhereUniqueInput | Prisma.TraceabilityTrackingOptionsWhereUniqueInput[]
  connect?: Prisma.TraceabilityTrackingOptionsWhereUniqueInput | Prisma.TraceabilityTrackingOptionsWhereUniqueInput[]
  update?: Prisma.TraceabilityTrackingOptionsUpdateWithWhereUniqueWithoutDefaultProducerAttributionsInput | Prisma.TraceabilityTrackingOptionsUpdateWithWhereUniqueWithoutDefaultProducerAttributionsInput[]
  updateMany?: Prisma.TraceabilityTrackingOptionsUpdateManyWithWhereWithoutDefaultProducerAttributionsInput | Prisma.TraceabilityTrackingOptionsUpdateManyWithWhereWithoutDefaultProducerAttributionsInput[]
  deleteMany?: Prisma.TraceabilityTrackingOptionsScalarWhereInput | Prisma.TraceabilityTrackingOptionsScalarWhereInput[]
}

export type TraceabilityTrackingOptionsCreateWithoutCompanyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  SystemCultureMode?: $Enums.SystemCultureMode
  DefaultProducerAttributions?: Prisma.ProducerCreateNestedManyWithoutTraceabilityTrackingOptionsInput
}

export type TraceabilityTrackingOptionsUncheckedCreateWithoutCompanyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  SystemCultureMode?: $Enums.SystemCultureMode
  DefaultProducerAttributions?: Prisma.ProducerUncheckedCreateNestedManyWithoutTraceabilityTrackingOptionsInput
}

export type TraceabilityTrackingOptionsCreateOrConnectWithoutCompanyInput = {
  where: Prisma.TraceabilityTrackingOptionsWhereUniqueInput
  create: Prisma.XOR<Prisma.TraceabilityTrackingOptionsCreateWithoutCompanyInput, Prisma.TraceabilityTrackingOptionsUncheckedCreateWithoutCompanyInput>
}

export type TraceabilityTrackingOptionsCreateManyCompanyInputEnvelope = {
  data: Prisma.TraceabilityTrackingOptionsCreateManyCompanyInput | Prisma.TraceabilityTrackingOptionsCreateManyCompanyInput[]
  skipDuplicates?: boolean
}

export type TraceabilityTrackingOptionsUpsertWithWhereUniqueWithoutCompanyInput = {
  where: Prisma.TraceabilityTrackingOptionsWhereUniqueInput
  update: Prisma.XOR<Prisma.TraceabilityTrackingOptionsUpdateWithoutCompanyInput, Prisma.TraceabilityTrackingOptionsUncheckedUpdateWithoutCompanyInput>
  create: Prisma.XOR<Prisma.TraceabilityTrackingOptionsCreateWithoutCompanyInput, Prisma.TraceabilityTrackingOptionsUncheckedCreateWithoutCompanyInput>
}

export type TraceabilityTrackingOptionsUpdateWithWhereUniqueWithoutCompanyInput = {
  where: Prisma.TraceabilityTrackingOptionsWhereUniqueInput
  data: Prisma.XOR<Prisma.TraceabilityTrackingOptionsUpdateWithoutCompanyInput, Prisma.TraceabilityTrackingOptionsUncheckedUpdateWithoutCompanyInput>
}

export type TraceabilityTrackingOptionsUpdateManyWithWhereWithoutCompanyInput = {
  where: Prisma.TraceabilityTrackingOptionsScalarWhereInput
  data: Prisma.XOR<Prisma.TraceabilityTrackingOptionsUpdateManyMutationInput, Prisma.TraceabilityTrackingOptionsUncheckedUpdateManyWithoutCompanyInput>
}

export type TraceabilityTrackingOptionsScalarWhereInput = {
  AND?: Prisma.TraceabilityTrackingOptionsScalarWhereInput | Prisma.TraceabilityTrackingOptionsScalarWhereInput[]
  OR?: Prisma.TraceabilityTrackingOptionsScalarWhereInput[]
  NOT?: Prisma.TraceabilityTrackingOptionsScalarWhereInput | Prisma.TraceabilityTrackingOptionsScalarWhereInput[]
  id?: Prisma.StringFilter<"TraceabilityTrackingOptions"> | string
  createdAt?: Prisma.DateTimeFilter<"TraceabilityTrackingOptions"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TraceabilityTrackingOptions"> | Date | string
  SystemCultureMode?: Prisma.EnumSystemCultureModeFilter<"TraceabilityTrackingOptions"> | $Enums.SystemCultureMode
  companyId?: Prisma.StringFilter<"TraceabilityTrackingOptions"> | string
}

export type TraceabilityTrackingOptionsCreateWithoutDefaultProducerAttributionsInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  SystemCultureMode?: $Enums.SystemCultureMode
  Company: Prisma.CompanyCreateNestedOneWithoutTraceabilityTrackingOptionsInput
}

export type TraceabilityTrackingOptionsUncheckedCreateWithoutDefaultProducerAttributionsInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  SystemCultureMode?: $Enums.SystemCultureMode
  companyId: string
}

export type TraceabilityTrackingOptionsCreateOrConnectWithoutDefaultProducerAttributionsInput = {
  where: Prisma.TraceabilityTrackingOptionsWhereUniqueInput
  create: Prisma.XOR<Prisma.TraceabilityTrackingOptionsCreateWithoutDefaultProducerAttributionsInput, Prisma.TraceabilityTrackingOptionsUncheckedCreateWithoutDefaultProducerAttributionsInput>
}

export type TraceabilityTrackingOptionsUpsertWithWhereUniqueWithoutDefaultProducerAttributionsInput = {
  where: Prisma.TraceabilityTrackingOptionsWhereUniqueInput
  update: Prisma.XOR<Prisma.TraceabilityTrackingOptionsUpdateWithoutDefaultProducerAttributionsInput, Prisma.TraceabilityTrackingOptionsUncheckedUpdateWithoutDefaultProducerAttributionsInput>
  create: Prisma.XOR<Prisma.TraceabilityTrackingOptionsCreateWithoutDefaultProducerAttributionsInput, Prisma.TraceabilityTrackingOptionsUncheckedCreateWithoutDefaultProducerAttributionsInput>
}

export type TraceabilityTrackingOptionsUpdateWithWhereUniqueWithoutDefaultProducerAttributionsInput = {
  where: Prisma.TraceabilityTrackingOptionsWhereUniqueInput
  data: Prisma.XOR<Prisma.TraceabilityTrackingOptionsUpdateWithoutDefaultProducerAttributionsInput, Prisma.TraceabilityTrackingOptionsUncheckedUpdateWithoutDefaultProducerAttributionsInput>
}

export type TraceabilityTrackingOptionsUpdateManyWithWhereWithoutDefaultProducerAttributionsInput = {
  where: Prisma.TraceabilityTrackingOptionsScalarWhereInput
  data: Prisma.XOR<Prisma.TraceabilityTrackingOptionsUpdateManyMutationInput, Prisma.TraceabilityTrackingOptionsUncheckedUpdateManyWithoutDefaultProducerAttributionsInput>
}

export type TraceabilityTrackingOptionsCreateManyCompanyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  SystemCultureMode?: $Enums.SystemCultureMode
}

export type TraceabilityTrackingOptionsUpdateWithoutCompanyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  SystemCultureMode?: Prisma.EnumSystemCultureModeFieldUpdateOperationsInput | $Enums.SystemCultureMode
  DefaultProducerAttributions?: Prisma.ProducerUpdateManyWithoutTraceabilityTrackingOptionsNestedInput
}

export type TraceabilityTrackingOptionsUncheckedUpdateWithoutCompanyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  SystemCultureMode?: Prisma.EnumSystemCultureModeFieldUpdateOperationsInput | $Enums.SystemCultureMode
  DefaultProducerAttributions?: Prisma.ProducerUncheckedUpdateManyWithoutTraceabilityTrackingOptionsNestedInput
}

export type TraceabilityTrackingOptionsUncheckedUpdateManyWithoutCompanyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  SystemCultureMode?: Prisma.EnumSystemCultureModeFieldUpdateOperationsInput | $Enums.SystemCultureMode
}

export type TraceabilityTrackingOptionsUpdateWithoutDefaultProducerAttributionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  SystemCultureMode?: Prisma.EnumSystemCultureModeFieldUpdateOperationsInput | $Enums.SystemCultureMode
  Company?: Prisma.CompanyUpdateOneRequiredWithoutTraceabilityTrackingOptionsNestedInput
}

export type TraceabilityTrackingOptionsUncheckedUpdateWithoutDefaultProducerAttributionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  SystemCultureMode?: Prisma.EnumSystemCultureModeFieldUpdateOperationsInput | $Enums.SystemCultureMode
  companyId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TraceabilityTrackingOptionsUncheckedUpdateManyWithoutDefaultProducerAttributionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  SystemCultureMode?: Prisma.EnumSystemCultureModeFieldUpdateOperationsInput | $Enums.SystemCultureMode
  companyId?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type TraceabilityTrackingOptionsCountOutputType
 */

export type TraceabilityTrackingOptionsCountOutputType = {
  DefaultProducerAttributions: number
}

export type TraceabilityTrackingOptionsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  DefaultProducerAttributions?: boolean | TraceabilityTrackingOptionsCountOutputTypeCountDefaultProducerAttributionsArgs
}

/**
 * TraceabilityTrackingOptionsCountOutputType without action
 */
export type TraceabilityTrackingOptionsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TraceabilityTrackingOptionsCountOutputType
   */
  select?: Prisma.TraceabilityTrackingOptionsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TraceabilityTrackingOptionsCountOutputType without action
 */
export type TraceabilityTrackingOptionsCountOutputTypeCountDefaultProducerAttributionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProducerWhereInput
}


export type TraceabilityTrackingOptionsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  SystemCultureMode?: boolean
  companyId?: boolean
  DefaultProducerAttributions?: boolean | Prisma.TraceabilityTrackingOptions$DefaultProducerAttributionsArgs<ExtArgs>
  Company?: boolean | Prisma.CompanyDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.TraceabilityTrackingOptionsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["traceabilityTrackingOptions"]>

export type TraceabilityTrackingOptionsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  SystemCultureMode?: boolean
  companyId?: boolean
  Company?: boolean | Prisma.CompanyDefaultArgs<ExtArgs>
}, ExtArgs["result"]["traceabilityTrackingOptions"]>

export type TraceabilityTrackingOptionsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  SystemCultureMode?: boolean
  companyId?: boolean
  Company?: boolean | Prisma.CompanyDefaultArgs<ExtArgs>
}, ExtArgs["result"]["traceabilityTrackingOptions"]>

export type TraceabilityTrackingOptionsSelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  SystemCultureMode?: boolean
  companyId?: boolean
}

export type TraceabilityTrackingOptionsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "SystemCultureMode" | "companyId", ExtArgs["result"]["traceabilityTrackingOptions"]>
export type TraceabilityTrackingOptionsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  DefaultProducerAttributions?: boolean | Prisma.TraceabilityTrackingOptions$DefaultProducerAttributionsArgs<ExtArgs>
  Company?: boolean | Prisma.CompanyDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.TraceabilityTrackingOptionsCountOutputTypeDefaultArgs<ExtArgs>
}
export type TraceabilityTrackingOptionsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Company?: boolean | Prisma.CompanyDefaultArgs<ExtArgs>
}
export type TraceabilityTrackingOptionsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Company?: boolean | Prisma.CompanyDefaultArgs<ExtArgs>
}

export type $TraceabilityTrackingOptionsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TraceabilityTrackingOptions"
  objects: {
    /**
     * This is the "default producers" relation
     */
    DefaultProducerAttributions: Prisma.$ProducerPayload<ExtArgs>[]
    Company: Prisma.$CompanyPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    updatedAt: Date
    SystemCultureMode: $Enums.SystemCultureMode
    companyId: string
  }, ExtArgs["result"]["traceabilityTrackingOptions"]>
  composites: {}
}

export type TraceabilityTrackingOptionsGetPayload<S extends boolean | null | undefined | TraceabilityTrackingOptionsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TraceabilityTrackingOptionsPayload, S>

export type TraceabilityTrackingOptionsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TraceabilityTrackingOptionsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TraceabilityTrackingOptionsCountAggregateInputType | true
  }

export interface TraceabilityTrackingOptionsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TraceabilityTrackingOptions'], meta: { name: 'TraceabilityTrackingOptions' } }
  /**
   * Find zero or one TraceabilityTrackingOptions that matches the filter.
   * @param {TraceabilityTrackingOptionsFindUniqueArgs} args - Arguments to find a TraceabilityTrackingOptions
   * @example
   * // Get one TraceabilityTrackingOptions
   * const traceabilityTrackingOptions = await prisma.traceabilityTrackingOptions.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TraceabilityTrackingOptionsFindUniqueArgs>(args: Prisma.SelectSubset<T, TraceabilityTrackingOptionsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TraceabilityTrackingOptionsClient<runtime.Types.Result.GetResult<Prisma.$TraceabilityTrackingOptionsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TraceabilityTrackingOptions that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TraceabilityTrackingOptionsFindUniqueOrThrowArgs} args - Arguments to find a TraceabilityTrackingOptions
   * @example
   * // Get one TraceabilityTrackingOptions
   * const traceabilityTrackingOptions = await prisma.traceabilityTrackingOptions.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TraceabilityTrackingOptionsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TraceabilityTrackingOptionsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TraceabilityTrackingOptionsClient<runtime.Types.Result.GetResult<Prisma.$TraceabilityTrackingOptionsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TraceabilityTrackingOptions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TraceabilityTrackingOptionsFindFirstArgs} args - Arguments to find a TraceabilityTrackingOptions
   * @example
   * // Get one TraceabilityTrackingOptions
   * const traceabilityTrackingOptions = await prisma.traceabilityTrackingOptions.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TraceabilityTrackingOptionsFindFirstArgs>(args?: Prisma.SelectSubset<T, TraceabilityTrackingOptionsFindFirstArgs<ExtArgs>>): Prisma.Prisma__TraceabilityTrackingOptionsClient<runtime.Types.Result.GetResult<Prisma.$TraceabilityTrackingOptionsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TraceabilityTrackingOptions that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TraceabilityTrackingOptionsFindFirstOrThrowArgs} args - Arguments to find a TraceabilityTrackingOptions
   * @example
   * // Get one TraceabilityTrackingOptions
   * const traceabilityTrackingOptions = await prisma.traceabilityTrackingOptions.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TraceabilityTrackingOptionsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TraceabilityTrackingOptionsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TraceabilityTrackingOptionsClient<runtime.Types.Result.GetResult<Prisma.$TraceabilityTrackingOptionsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TraceabilityTrackingOptions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TraceabilityTrackingOptionsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TraceabilityTrackingOptions
   * const traceabilityTrackingOptions = await prisma.traceabilityTrackingOptions.findMany()
   * 
   * // Get first 10 TraceabilityTrackingOptions
   * const traceabilityTrackingOptions = await prisma.traceabilityTrackingOptions.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const traceabilityTrackingOptionsWithIdOnly = await prisma.traceabilityTrackingOptions.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TraceabilityTrackingOptionsFindManyArgs>(args?: Prisma.SelectSubset<T, TraceabilityTrackingOptionsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TraceabilityTrackingOptionsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TraceabilityTrackingOptions.
   * @param {TraceabilityTrackingOptionsCreateArgs} args - Arguments to create a TraceabilityTrackingOptions.
   * @example
   * // Create one TraceabilityTrackingOptions
   * const TraceabilityTrackingOptions = await prisma.traceabilityTrackingOptions.create({
   *   data: {
   *     // ... data to create a TraceabilityTrackingOptions
   *   }
   * })
   * 
   */
  create<T extends TraceabilityTrackingOptionsCreateArgs>(args: Prisma.SelectSubset<T, TraceabilityTrackingOptionsCreateArgs<ExtArgs>>): Prisma.Prisma__TraceabilityTrackingOptionsClient<runtime.Types.Result.GetResult<Prisma.$TraceabilityTrackingOptionsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TraceabilityTrackingOptions.
   * @param {TraceabilityTrackingOptionsCreateManyArgs} args - Arguments to create many TraceabilityTrackingOptions.
   * @example
   * // Create many TraceabilityTrackingOptions
   * const traceabilityTrackingOptions = await prisma.traceabilityTrackingOptions.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TraceabilityTrackingOptionsCreateManyArgs>(args?: Prisma.SelectSubset<T, TraceabilityTrackingOptionsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TraceabilityTrackingOptions and returns the data saved in the database.
   * @param {TraceabilityTrackingOptionsCreateManyAndReturnArgs} args - Arguments to create many TraceabilityTrackingOptions.
   * @example
   * // Create many TraceabilityTrackingOptions
   * const traceabilityTrackingOptions = await prisma.traceabilityTrackingOptions.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TraceabilityTrackingOptions and only return the `id`
   * const traceabilityTrackingOptionsWithIdOnly = await prisma.traceabilityTrackingOptions.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TraceabilityTrackingOptionsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TraceabilityTrackingOptionsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TraceabilityTrackingOptionsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TraceabilityTrackingOptions.
   * @param {TraceabilityTrackingOptionsDeleteArgs} args - Arguments to delete one TraceabilityTrackingOptions.
   * @example
   * // Delete one TraceabilityTrackingOptions
   * const TraceabilityTrackingOptions = await prisma.traceabilityTrackingOptions.delete({
   *   where: {
   *     // ... filter to delete one TraceabilityTrackingOptions
   *   }
   * })
   * 
   */
  delete<T extends TraceabilityTrackingOptionsDeleteArgs>(args: Prisma.SelectSubset<T, TraceabilityTrackingOptionsDeleteArgs<ExtArgs>>): Prisma.Prisma__TraceabilityTrackingOptionsClient<runtime.Types.Result.GetResult<Prisma.$TraceabilityTrackingOptionsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TraceabilityTrackingOptions.
   * @param {TraceabilityTrackingOptionsUpdateArgs} args - Arguments to update one TraceabilityTrackingOptions.
   * @example
   * // Update one TraceabilityTrackingOptions
   * const traceabilityTrackingOptions = await prisma.traceabilityTrackingOptions.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TraceabilityTrackingOptionsUpdateArgs>(args: Prisma.SelectSubset<T, TraceabilityTrackingOptionsUpdateArgs<ExtArgs>>): Prisma.Prisma__TraceabilityTrackingOptionsClient<runtime.Types.Result.GetResult<Prisma.$TraceabilityTrackingOptionsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TraceabilityTrackingOptions.
   * @param {TraceabilityTrackingOptionsDeleteManyArgs} args - Arguments to filter TraceabilityTrackingOptions to delete.
   * @example
   * // Delete a few TraceabilityTrackingOptions
   * const { count } = await prisma.traceabilityTrackingOptions.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TraceabilityTrackingOptionsDeleteManyArgs>(args?: Prisma.SelectSubset<T, TraceabilityTrackingOptionsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TraceabilityTrackingOptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TraceabilityTrackingOptionsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TraceabilityTrackingOptions
   * const traceabilityTrackingOptions = await prisma.traceabilityTrackingOptions.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TraceabilityTrackingOptionsUpdateManyArgs>(args: Prisma.SelectSubset<T, TraceabilityTrackingOptionsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TraceabilityTrackingOptions and returns the data updated in the database.
   * @param {TraceabilityTrackingOptionsUpdateManyAndReturnArgs} args - Arguments to update many TraceabilityTrackingOptions.
   * @example
   * // Update many TraceabilityTrackingOptions
   * const traceabilityTrackingOptions = await prisma.traceabilityTrackingOptions.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TraceabilityTrackingOptions and only return the `id`
   * const traceabilityTrackingOptionsWithIdOnly = await prisma.traceabilityTrackingOptions.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TraceabilityTrackingOptionsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TraceabilityTrackingOptionsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TraceabilityTrackingOptionsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TraceabilityTrackingOptions.
   * @param {TraceabilityTrackingOptionsUpsertArgs} args - Arguments to update or create a TraceabilityTrackingOptions.
   * @example
   * // Update or create a TraceabilityTrackingOptions
   * const traceabilityTrackingOptions = await prisma.traceabilityTrackingOptions.upsert({
   *   create: {
   *     // ... data to create a TraceabilityTrackingOptions
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TraceabilityTrackingOptions we want to update
   *   }
   * })
   */
  upsert<T extends TraceabilityTrackingOptionsUpsertArgs>(args: Prisma.SelectSubset<T, TraceabilityTrackingOptionsUpsertArgs<ExtArgs>>): Prisma.Prisma__TraceabilityTrackingOptionsClient<runtime.Types.Result.GetResult<Prisma.$TraceabilityTrackingOptionsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TraceabilityTrackingOptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TraceabilityTrackingOptionsCountArgs} args - Arguments to filter TraceabilityTrackingOptions to count.
   * @example
   * // Count the number of TraceabilityTrackingOptions
   * const count = await prisma.traceabilityTrackingOptions.count({
   *   where: {
   *     // ... the filter for the TraceabilityTrackingOptions we want to count
   *   }
   * })
  **/
  count<T extends TraceabilityTrackingOptionsCountArgs>(
    args?: Prisma.Subset<T, TraceabilityTrackingOptionsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TraceabilityTrackingOptionsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TraceabilityTrackingOptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TraceabilityTrackingOptionsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TraceabilityTrackingOptionsAggregateArgs>(args: Prisma.Subset<T, TraceabilityTrackingOptionsAggregateArgs>): Prisma.PrismaPromise<GetTraceabilityTrackingOptionsAggregateType<T>>

  /**
   * Group by TraceabilityTrackingOptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TraceabilityTrackingOptionsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TraceabilityTrackingOptionsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TraceabilityTrackingOptionsGroupByArgs['orderBy'] }
      : { orderBy?: TraceabilityTrackingOptionsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TraceabilityTrackingOptionsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTraceabilityTrackingOptionsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TraceabilityTrackingOptions model
 */
readonly fields: TraceabilityTrackingOptionsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TraceabilityTrackingOptions.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TraceabilityTrackingOptionsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  DefaultProducerAttributions<T extends Prisma.TraceabilityTrackingOptions$DefaultProducerAttributionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TraceabilityTrackingOptions$DefaultProducerAttributionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProducerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  Company<T extends Prisma.CompanyDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CompanyDefaultArgs<ExtArgs>>): Prisma.Prisma__CompanyClient<runtime.Types.Result.GetResult<Prisma.$CompanyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TraceabilityTrackingOptions model
 */
export interface TraceabilityTrackingOptionsFieldRefs {
  readonly id: Prisma.FieldRef<"TraceabilityTrackingOptions", 'String'>
  readonly createdAt: Prisma.FieldRef<"TraceabilityTrackingOptions", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TraceabilityTrackingOptions", 'DateTime'>
  readonly SystemCultureMode: Prisma.FieldRef<"TraceabilityTrackingOptions", 'SystemCultureMode'>
  readonly companyId: Prisma.FieldRef<"TraceabilityTrackingOptions", 'String'>
}
    

// Custom InputTypes
/**
 * TraceabilityTrackingOptions findUnique
 */
export type TraceabilityTrackingOptionsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TraceabilityTrackingOptions
   */
  select?: Prisma.TraceabilityTrackingOptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TraceabilityTrackingOptions
   */
  omit?: Prisma.TraceabilityTrackingOptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TraceabilityTrackingOptionsInclude<ExtArgs> | null
  /**
   * Filter, which TraceabilityTrackingOptions to fetch.
   */
  where: Prisma.TraceabilityTrackingOptionsWhereUniqueInput
}

/**
 * TraceabilityTrackingOptions findUniqueOrThrow
 */
export type TraceabilityTrackingOptionsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TraceabilityTrackingOptions
   */
  select?: Prisma.TraceabilityTrackingOptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TraceabilityTrackingOptions
   */
  omit?: Prisma.TraceabilityTrackingOptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TraceabilityTrackingOptionsInclude<ExtArgs> | null
  /**
   * Filter, which TraceabilityTrackingOptions to fetch.
   */
  where: Prisma.TraceabilityTrackingOptionsWhereUniqueInput
}

/**
 * TraceabilityTrackingOptions findFirst
 */
export type TraceabilityTrackingOptionsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TraceabilityTrackingOptions
   */
  select?: Prisma.TraceabilityTrackingOptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TraceabilityTrackingOptions
   */
  omit?: Prisma.TraceabilityTrackingOptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TraceabilityTrackingOptionsInclude<ExtArgs> | null
  /**
   * Filter, which TraceabilityTrackingOptions to fetch.
   */
  where?: Prisma.TraceabilityTrackingOptionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TraceabilityTrackingOptions to fetch.
   */
  orderBy?: Prisma.TraceabilityTrackingOptionsOrderByWithRelationInput | Prisma.TraceabilityTrackingOptionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TraceabilityTrackingOptions.
   */
  cursor?: Prisma.TraceabilityTrackingOptionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TraceabilityTrackingOptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TraceabilityTrackingOptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TraceabilityTrackingOptions.
   */
  distinct?: Prisma.TraceabilityTrackingOptionsScalarFieldEnum | Prisma.TraceabilityTrackingOptionsScalarFieldEnum[]
}

/**
 * TraceabilityTrackingOptions findFirstOrThrow
 */
export type TraceabilityTrackingOptionsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TraceabilityTrackingOptions
   */
  select?: Prisma.TraceabilityTrackingOptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TraceabilityTrackingOptions
   */
  omit?: Prisma.TraceabilityTrackingOptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TraceabilityTrackingOptionsInclude<ExtArgs> | null
  /**
   * Filter, which TraceabilityTrackingOptions to fetch.
   */
  where?: Prisma.TraceabilityTrackingOptionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TraceabilityTrackingOptions to fetch.
   */
  orderBy?: Prisma.TraceabilityTrackingOptionsOrderByWithRelationInput | Prisma.TraceabilityTrackingOptionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TraceabilityTrackingOptions.
   */
  cursor?: Prisma.TraceabilityTrackingOptionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TraceabilityTrackingOptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TraceabilityTrackingOptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TraceabilityTrackingOptions.
   */
  distinct?: Prisma.TraceabilityTrackingOptionsScalarFieldEnum | Prisma.TraceabilityTrackingOptionsScalarFieldEnum[]
}

/**
 * TraceabilityTrackingOptions findMany
 */
export type TraceabilityTrackingOptionsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TraceabilityTrackingOptions
   */
  select?: Prisma.TraceabilityTrackingOptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TraceabilityTrackingOptions
   */
  omit?: Prisma.TraceabilityTrackingOptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TraceabilityTrackingOptionsInclude<ExtArgs> | null
  /**
   * Filter, which TraceabilityTrackingOptions to fetch.
   */
  where?: Prisma.TraceabilityTrackingOptionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TraceabilityTrackingOptions to fetch.
   */
  orderBy?: Prisma.TraceabilityTrackingOptionsOrderByWithRelationInput | Prisma.TraceabilityTrackingOptionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TraceabilityTrackingOptions.
   */
  cursor?: Prisma.TraceabilityTrackingOptionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TraceabilityTrackingOptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TraceabilityTrackingOptions.
   */
  skip?: number
  distinct?: Prisma.TraceabilityTrackingOptionsScalarFieldEnum | Prisma.TraceabilityTrackingOptionsScalarFieldEnum[]
}

/**
 * TraceabilityTrackingOptions create
 */
export type TraceabilityTrackingOptionsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TraceabilityTrackingOptions
   */
  select?: Prisma.TraceabilityTrackingOptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TraceabilityTrackingOptions
   */
  omit?: Prisma.TraceabilityTrackingOptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TraceabilityTrackingOptionsInclude<ExtArgs> | null
  /**
   * The data needed to create a TraceabilityTrackingOptions.
   */
  data: Prisma.XOR<Prisma.TraceabilityTrackingOptionsCreateInput, Prisma.TraceabilityTrackingOptionsUncheckedCreateInput>
}

/**
 * TraceabilityTrackingOptions createMany
 */
export type TraceabilityTrackingOptionsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TraceabilityTrackingOptions.
   */
  data: Prisma.TraceabilityTrackingOptionsCreateManyInput | Prisma.TraceabilityTrackingOptionsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TraceabilityTrackingOptions createManyAndReturn
 */
export type TraceabilityTrackingOptionsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TraceabilityTrackingOptions
   */
  select?: Prisma.TraceabilityTrackingOptionsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TraceabilityTrackingOptions
   */
  omit?: Prisma.TraceabilityTrackingOptionsOmit<ExtArgs> | null
  /**
   * The data used to create many TraceabilityTrackingOptions.
   */
  data: Prisma.TraceabilityTrackingOptionsCreateManyInput | Prisma.TraceabilityTrackingOptionsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TraceabilityTrackingOptionsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TraceabilityTrackingOptions update
 */
export type TraceabilityTrackingOptionsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TraceabilityTrackingOptions
   */
  select?: Prisma.TraceabilityTrackingOptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TraceabilityTrackingOptions
   */
  omit?: Prisma.TraceabilityTrackingOptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TraceabilityTrackingOptionsInclude<ExtArgs> | null
  /**
   * The data needed to update a TraceabilityTrackingOptions.
   */
  data: Prisma.XOR<Prisma.TraceabilityTrackingOptionsUpdateInput, Prisma.TraceabilityTrackingOptionsUncheckedUpdateInput>
  /**
   * Choose, which TraceabilityTrackingOptions to update.
   */
  where: Prisma.TraceabilityTrackingOptionsWhereUniqueInput
}

/**
 * TraceabilityTrackingOptions updateMany
 */
export type TraceabilityTrackingOptionsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TraceabilityTrackingOptions.
   */
  data: Prisma.XOR<Prisma.TraceabilityTrackingOptionsUpdateManyMutationInput, Prisma.TraceabilityTrackingOptionsUncheckedUpdateManyInput>
  /**
   * Filter which TraceabilityTrackingOptions to update
   */
  where?: Prisma.TraceabilityTrackingOptionsWhereInput
  /**
   * Limit how many TraceabilityTrackingOptions to update.
   */
  limit?: number
}

/**
 * TraceabilityTrackingOptions updateManyAndReturn
 */
export type TraceabilityTrackingOptionsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TraceabilityTrackingOptions
   */
  select?: Prisma.TraceabilityTrackingOptionsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TraceabilityTrackingOptions
   */
  omit?: Prisma.TraceabilityTrackingOptionsOmit<ExtArgs> | null
  /**
   * The data used to update TraceabilityTrackingOptions.
   */
  data: Prisma.XOR<Prisma.TraceabilityTrackingOptionsUpdateManyMutationInput, Prisma.TraceabilityTrackingOptionsUncheckedUpdateManyInput>
  /**
   * Filter which TraceabilityTrackingOptions to update
   */
  where?: Prisma.TraceabilityTrackingOptionsWhereInput
  /**
   * Limit how many TraceabilityTrackingOptions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TraceabilityTrackingOptionsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TraceabilityTrackingOptions upsert
 */
export type TraceabilityTrackingOptionsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TraceabilityTrackingOptions
   */
  select?: Prisma.TraceabilityTrackingOptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TraceabilityTrackingOptions
   */
  omit?: Prisma.TraceabilityTrackingOptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TraceabilityTrackingOptionsInclude<ExtArgs> | null
  /**
   * The filter to search for the TraceabilityTrackingOptions to update in case it exists.
   */
  where: Prisma.TraceabilityTrackingOptionsWhereUniqueInput
  /**
   * In case the TraceabilityTrackingOptions found by the `where` argument doesn't exist, create a new TraceabilityTrackingOptions with this data.
   */
  create: Prisma.XOR<Prisma.TraceabilityTrackingOptionsCreateInput, Prisma.TraceabilityTrackingOptionsUncheckedCreateInput>
  /**
   * In case the TraceabilityTrackingOptions was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TraceabilityTrackingOptionsUpdateInput, Prisma.TraceabilityTrackingOptionsUncheckedUpdateInput>
}

/**
 * TraceabilityTrackingOptions delete
 */
export type TraceabilityTrackingOptionsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TraceabilityTrackingOptions
   */
  select?: Prisma.TraceabilityTrackingOptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TraceabilityTrackingOptions
   */
  omit?: Prisma.TraceabilityTrackingOptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TraceabilityTrackingOptionsInclude<ExtArgs> | null
  /**
   * Filter which TraceabilityTrackingOptions to delete.
   */
  where: Prisma.TraceabilityTrackingOptionsWhereUniqueInput
}

/**
 * TraceabilityTrackingOptions deleteMany
 */
export type TraceabilityTrackingOptionsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TraceabilityTrackingOptions to delete
   */
  where?: Prisma.TraceabilityTrackingOptionsWhereInput
  /**
   * Limit how many TraceabilityTrackingOptions to delete.
   */
  limit?: number
}

/**
 * TraceabilityTrackingOptions.DefaultProducerAttributions
 */
export type TraceabilityTrackingOptions$DefaultProducerAttributionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Producer
   */
  select?: Prisma.ProducerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Producer
   */
  omit?: Prisma.ProducerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProducerInclude<ExtArgs> | null
  where?: Prisma.ProducerWhereInput
  orderBy?: Prisma.ProducerOrderByWithRelationInput | Prisma.ProducerOrderByWithRelationInput[]
  cursor?: Prisma.ProducerWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProducerScalarFieldEnum | Prisma.ProducerScalarFieldEnum[]
}

/**
 * TraceabilityTrackingOptions without action
 */
export type TraceabilityTrackingOptionsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TraceabilityTrackingOptions
   */
  select?: Prisma.TraceabilityTrackingOptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TraceabilityTrackingOptions
   */
  omit?: Prisma.TraceabilityTrackingOptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TraceabilityTrackingOptionsInclude<ExtArgs> | null
}
